#Alex Paquette 25/09/2023
#Makefile for Lab Two

CC = g++
FILES = Semaphore.cpp rendezvous.cpp
FLAGS = -Wall -o rendezvous

RENDEZVOUS: $(FILES)
	$(CC) $(FILES) $(FLAGS)

CLEAN:
	rm rendezvous a.out *.o