#Alex Paquette 25/09/2023
#Makefile for Lab One

CC = g++
FILES = helloThreads.cpp Semaphore.cpp
FLAGS = -Wall -o helloThreads

HELLOTHREADS: $(FILES)
	$(CC) $(FLAGS) $(FILES)

CLEAN:
	rm helloThreads a.out *.o